apiVersion: v1
kind: Service
metadata:
  name: devops4-service
spec:
  type: LoadBalancer # Minikube üzerinde tarayıcıdan erişebilmek için LoadBalancer kullanıyoruz
  selector:
    app: devops4
  ports:
    - port: 8081
      targetPort: 8081